name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cli/gh-extension-precompile@v1
        with:
          generate_attestations: true
          go_version_file: go.mod
      - name: Set up environment for cgo
        run: |
          export CGO_ENABLED=1
          echo "CGO_ENABLED=1 has been set"
