name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 1 # Globally enable cgo
    steps:
      - uses: actions/checkout@v4
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
      - uses: cli/gh-extension-precompile@v1
        with:
          generate_attestations: true
          go_version_file: go.mod
      - name: Verify cgo setup
        run: |
          echo "CGO_ENABLED=$CGO_ENABLED"
          go env
